### ISSUE TITLE
Capitalization changes

### ISSUE THREAD

**Issue by HR19** [Seeed-Studio/Seeed_Elink_Shield#1]
In epdif.h line: 

`#include "arduino.h"`

needs to be changed to

`#include "Arduino.h"`

And in epdif.cpp line: 

`#include <spi.h>`

needs to be changed to:

`#include <SPI.h>`

**Comment by lakshanthad** [comment]
It is done.

https://github.com/Seeed-Studio/Seeed_Elink_Shield/commit/dc0b450e2ea4e29d52d85e056c7f48eba88515a2

**Comment by HR19** [comment]
Thanks!
